server:
  port: 8082
# This will return the error message in the response body when we throw it
  error:
    include-message: always
spring:
  application:
    name: teacher-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  management:
    endpoints:
      web:
        exposure:
          include: '*'
# For Spring Data JPA Connection
  jpa:
    hibernate:
#     This has to type  update, otherwise it will try to create new tables.
      ddl-auto: update
#   This will print Hibernate generated queries on the console for us to see.
    show-sql: true
  datasource:
#   You should make a Database in your system name "web_academyDB" before starting this project.
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/web_academyDB
    username: root
#   Might need to change this depending on your SQL settings
    password: mysqlroot123
    driver-class-name: com.mysql.cj.jdbc.Driver
